Repository AY2021S1-CS2103T-T12-1/tp, pull requests merged in 2020-10, with the labels that each got.

#90 Summary help window and Getting started window
  README.md
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/wincenttjoi.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/commands/help/HelpCommand.java
  src/main/java/seedu/address/logic/commands/help/HelpStartCommand.java
  src/main/java/seedu/address/logic/commands/help/HelpSummaryCommand.java
  src/main/java/seedu/address/logic/commands/results/CommandResult.java
  src/main/java/seedu/address/logic/commands/results/HelpCommandResult.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/InventoryBookParser.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PreviewWindow.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/ItemListCard.fxml
  src/main/resources/view/ItemListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PreviewWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/InventoryBookParserTest.java
Labels: priority.Medium

#106 Reorganise GUI Layout
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/ui/DeliveryCard.java
  src/main/java/seedu/address/ui/DeliveryListPanel.java
  src/main/java/seedu/address/ui/ItemCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DeliveryListCard.fxml
  src/main/resources/view/DeliveryListPanel.fxml
  src/main/resources/view/ItemListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#111 Get branch-delivery up to date with master
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/model/inventorymodel/InventoryModel.java
  src/main/java/seedu/address/model/inventorymodel/InventoryModelManager.java
  src/main/java/seedu/address/ui/DeliveryCard.java
  src/main/java/seedu/address/ui/DeliveryListPanel.java
  src/main/java/seedu/address/ui/ItemCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DeliveryListCard.fxml
  src/main/resources/view/DeliveryListPanel.fxml
  src/main/resources/view/ItemListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#113 Partial Remove command test
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
  src/test/java/seedu/address/logic/commands/RemoveCommandTest.java
  src/test/java/seedu/address/logic/parser/InventoryBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveCommandParserTest.java
Labels: priority.Medium, severity.Low

#114 Remove command test equals
  .github/workflows/gradle.yml
  docs/UserGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/deliverycommand/DeliveryFindCommand.java
  src/main/java/seedu/address/logic/commands/deliverycommand/DeliveryListCommand.java
  src/main/java/seedu/address/logic/commands/itemcommand/ItemAddCommand.java
  src/main/java/seedu/address/logic/commands/itemcommand/ItemRemoveCommand.java
  src/main/java/seedu/address/logic/parser/OneShelfBookParser.java
  src/main/java/seedu/address/logic/parser/itemparser/RemoveCommandParser.java
  src/main/java/seedu/address/ui/ItemCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeliveryListCommandTest.java
  src/test/java/seedu/address/logic/commands/ItemRemoveCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveCommandTest.java
  src/test/java/seedu/address/logic/parser/ItemRemoveCommandParserTest.java
  src/test/java/seedu/address/logic/parser/OneShelfBookParserTest.java
  src/test/java/seedu/address/testutil/DeliveryBuilder.java
  src/test/java/seedu/address/testutil/TypicalDeliveries.java
  src/test/java/seedu/address/testutil/TypicalItems.java
Labels: priority.Medium, type.Task

#124 Delivery model test
  src/main/java/seedu/address/model/delivery/Order.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/delivery/AddressTest.java
  src/test/java/seedu/address/model/delivery/DeliveryContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/delivery/DeliveryNameTest.java
  src/test/java/seedu/address/model/delivery/DeliveryTest.java
  src/test/java/seedu/address/model/delivery/OrderTest.java
  src/test/java/seedu/address/model/delivery/PhoneTest.java
  src/test/java/seedu/address/model/delivery/UniqueDeliveryListTest.java
Labels: priority.Medium, type.Enhancement

#143 Gui datetime corner
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/StatusBarFooter.fxml
Labels: priority.Medium, type.Enhancement, type.Task

#144 Delivery clear command
  src/main/java/seedu/address/logic/commands/deliverycommand/DeliveryClearCommand.java
  src/main/java/seedu/address/logic/commands/deliverycommand/DeliveryCommand.java
  src/main/java/seedu/address/logic/commands/itemcommand/ItemCommand.java
  src/main/java/seedu/address/logic/parser/OneShelfBookParser.java
  src/test/java/seedu/address/logic/commands/deliverycommand/DeliveryClearCommandTest.java
  src/test/java/seedu/address/logic/parser/OneShelfBookParserTest.java
Labels: priority.Medium, type.Task

#162 DG for UI component
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: priority.High, type.Task

#165 Delivery edit delete
  src/main/java/seedu/address/logic/commands/deliverycommand/DeliveryDeleteCommand.java
  src/main/java/seedu/address/logic/commands/deliverycommand/DeliveryEditCommand.java
  src/main/java/seedu/address/logic/commands/deliverycommand/DeliveryListCommand.java
  src/main/java/seedu/address/logic/parser/OneShelfBookParser.java
  src/main/java/seedu/address/logic/parser/deliveryparser/DeliveryDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/deliveryparser/DeliveryEditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/deliverycommand/DeliveryDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/deliverycommand/DeliveryEditCommandTest.java
  src/test/java/seedu/address/logic/commands/deliverycommand/EditDeliveryDescriptorTest.java
  src/test/java/seedu/address/logic/parser/OneShelfBookParserTest.java
  src/test/java/seedu/address/logic/parser/deliveryparser/DeliveryDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/deliveryparser/DeliveryEditCommandParserTest.java
  src/test/java/seedu/address/testutil/DeliveryUtil.java
  src/test/java/seedu/address/testutil/EditDeliveryDescriptorBuilder.java
Labels: priority.High, type.Task

#168 Update README and UG
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiHelpStart.png
  docs/images/UiWireframe.png
  docs/team/wincenttjoi.md
Labels: priority.Medium, type.Enhancement

#187 Update readme
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiHelpStart.png
  src/main/java/seedu/address/commons/core/Messages.java
Labels: priority.High, type.Task

#188 Update UG based on previous PR
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
Labels: priority.High, type.Task

#191 Fix summary table UG
  docs/UserGuide.md
Labels: priority.High, type.Task

#171 fix find-command bug by allowing more than 2 field
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/ItemFindCommandSequenceDiagram.puml
  docs/images/FindActivityDiagram.png
  docs/images/ItemFindCommandSequenceDiagram.png
  docs/team/wincenttjoi.md
  docs/team/zeranium97.md
  src/main/java/seedu/address/logic/commands/deliverycommand/DeliveryAddCommand.java
  src/main/java/seedu/address/logic/commands/deliverycommand/DeliveryFindCommand.java
  src/main/java/seedu/address/logic/commands/itemcommand/ItemAddCommand.java
  src/main/java/seedu/address/logic/commands/itemcommand/ItemFindCommand.java
  src/main/java/seedu/address/logic/parser/deliveryparser/DeliveryFindCommandParser.java
  src/main/java/seedu/address/logic/parser/itemparser/ItemFindCommandParser.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/model/delivery/DeliveryContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/delivery/predicate/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/delivery/predicate/DeliveryNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/delivery/predicate/OrderContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/delivery/predicate/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/item/Item.java
  src/main/java/seedu/address/model/item/ItemContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/item/predicate/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/item/predicate/SupplierContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/item/predicate/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/deliverycommand/DeliveryFindCommandTest.java
  src/test/java/seedu/address/logic/commands/itemcommand/ItemFindCommandTest.java
  src/test/java/seedu/address/logic/parser/OneShelfBookParserTest.java
  src/test/java/seedu/address/logic/parser/deliveryparser/DeliveryFindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/itemparser/ItemFindCommandParserTest.java
  src/test/java/seedu/address/model/InventoryModelManagerTest.java
  src/test/java/seedu/address/model/delivery/DeliveryContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/delivery/predicate/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/delivery/predicate/DeliveryNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/delivery/predicate/OrderContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/delivery/predicate/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/item/ItemContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/item/predicate/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/item/predicate/SupplierContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/item/predicate/TagContainsKeywordsPredicateTest.java
Labels: severity.Medium, type.Bug

#192 Change Ui.png, and fix UG summary table
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiWithAnnotation.png
Labels: severity.Medium, type.Task

#195 Wincent's DG update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/HelpActivityDiagram.puml
  docs/images/HelpActivityDiagram.png
  docs/team/wincenttjoi.md
  src/main/java/seedu/address/logic/commands/results/CommandResult.java
Labels: priority.High, type.Task

#204 Wincent's User Guide
  .github/workflows/gradle.yml
  README.md
  docs/UserGuide.md
  docs/images/UG_delete_eg1_step1.PNG
  docs/images/UG_delete_eg1_step2.PNG
  docs/images/UG_delete_eg2_step1.PNG
  docs/images/UG_delete_eg2_step2.PNG
  docs/images/UG_delete_eg2_step3.PNG
  docs/images/Ui.png
  docs/images/UiV1.2.png
  docs/images/UiWithAnnotation.png
  docs/images/UiWithAnnotationV1.2.png
  docs/images/add-d_eg1.1.PNG
  docs/images/add-d_eg1.2.PNG
  docs/images/add-i_eg1.1.PNG
  docs/images/add-i_eg1.2.PNG
  docs/images/add-i_eg1.3.PNG
  docs/index.md
  docs/team/wincenttjoi.md
  src/main/java/seedu/address/logic/commands/deliverycommand/DeliveryAddCommand.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/model/item/Item.java
Labels: priority.High, type.Task

#207 Update DG and UG
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
Labels: priority.High, type.Task
